### ISSUE TITLE
🔥 THE. CSTK. BURN. (and contract upgrades)

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#270]
- [x] #271 - Compile new Registry list
- [x] #261 - Deploy upgraded contracts
- [x] #262 - Update Swissmem dApp to fetch pending score from Registry contract
- [x] #263 - Do a block screen (Elmo theme/meme)
- [x] #264 - Test Swissmem dApp with fake user/pending score
- [x] #265 - Populate new Registry contract
- [x] #266 - Update bridge server with new Minter address
- [x] #267 - Give Minter access to call DAO mint mint function
- [x] #268 - Test payment / token generation flow
- [x] #269 - Final step: Shut down old contracts
