### ISSUE TITLE
Automate the minting of CSLove

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#306]
Right now Ivy and Tam spend hours every week pulling data out of Giveth to send CSLove to people... this involves

- [ ] Sending an Email
- [ ] Sending Rinkeby ETH
- [ ] Sending Rinkeby CSlove

**Comment by kristoferlund** [comment]
## Todo
Automate the minting and integrate with dApp at the final step of the activation flow.

Bridge server: 
- Mint CSLOVE tokens
- Send Rinkeby ETH

**Comment by kristoferlund** [comment]
Criteria to fill before sending CSLOVE:
1. Check to see that donation is at least 450 DAI
2. Check that there is no previous transaction (transfer event - user gets CSLOVE only one time)

Then send tokens:
1. Send 1 CSLOVE token to user
2. Send 0.05 Rinkeby ETH to user
3. Send email to info@commonsstack.org with notification and user ETH adress

**Comment by tamarandom** [comment]
Credit where due it's ALL @iviangita now. It also takes about 30 minutes. BUT .... 

One of the other big wins here is **immediate gratification** for the new member. :) The manual process happens once a week. It would be a a better experience to pay dues and be able to then order swag straight away!

**Comment by tamarandom** [comment]
We should remove Step 3 "Send email to info@commonsstack.org with notification and user ETH address"

The manual process can still work if @knobsdao wants there to be a personal reach out to new members following activation.

**Comment by kristoferlund** [comment]
> We should remove Step 3 "Send email to [info@commonsstack.org](mailto:info@commonsstack.org) with notification and user ETH address"
> 
> The manual process can still work if @knobsdao wants there to be a personal reach out to new members following activation.

@tamarandom The email is for notifying @knobsdao etc that there is a new member so that he can easier do the personal reachout. No need to manually scan the blockchain contract for new transactions / new members any more.
